#ifndef OSPRD_H
#define OSPRD_H

// ioctl constants
#define OSPRDIOCACQUIRE		42
#define OSPRDIOCTRYACQUIRE	43
#define OSPRDIOCRELEASE		44
#define OSPRDIOCNOTIFICATION 45
#define OSPRDIOCWAKENOTIFICATION 46

#endif
